### ISSUE TITLE
TypeError: writable must be a WritableStream

### ISSUE THREAD

**Issue by bradisbell** [stardazed/sd-streams#4]
I think I'm misunderstanding some usage of this polyfill.  I've added the following before my scripts:

        <script src="//unpkg.com/@stardazed/streams-polyfill/dist/sd-streams-polyfill.min.js"></script>

In my script, I have a simple Fetch:

    fetch(url).then((res) => {
      if (!res.ok) {
        throw res;
      }

      return res.body.pipeThrough(new TextDecoderStream());
    });

This causes the error:

> Uncaught (in promise) TypeError: writable must be a WritableStream
>     at SDReadableStream.pipeThrough (sd-streams-polyfill.min.js:7)

Any thoughts on what I'm missing?  Thanks.

**Comment by zenmumbler** [comment]
Oh, I missed this completely. This is an actual bug in the polyfill. At the time of last release, none of the browsers had a native implementation of TextEncoderStream/TextDecoderStream so the polyfill would also be applied.

Now Chrome has its own implementation but not yet the full Streams implementation and the polyfill incorrectly does not overwrite the native version by its own in this case. Mixing native and polyfilled streams will give issues in certain calls.

I will update this and ping back here when I've fixed the issue.

**Comment by zenmumbler** [comment]
I have published v2.0.1 that solves this issue. The code you posted above now functions as expected.
