### ISSUE TITLE
Missing type definitions in streams-polyfill?

### ISSUE THREAD

**Issue by kcoop** [stardazed/sd-streams#5]
Thanks for a useful project!

I'm trying to use streams-polyfill in Typescript 3.8 node project, and tsc isn't finding types for streaming classes (I'm referencing WritableStream, TextDecoderStream, and TransformStream). 

I've tried both adding the import you suggest

`import "@stardazed/streams-polyfill;`

as well as explicitly importing the types 

`import { WritableStream, TextDecoderStream, and TransformStream } from "@stardazed/streams-polyfill;`

I understand from your readme that Typescript > 3.2 is supposed to supply these. Is there some tsconfig magic I need to do to have that work?

**Comment by kcoop** [comment]
Hmm, changing lib from esnext to es2017 in tsconfig fixed it. Would have thought esnext would still include the types.

**Comment by kcoop** [comment]
Yeah, it's weird. There are a few other issues happening, not sure if they're related: I had to explicitly add a global for TextDecoder (which in node is util.TextDecoder):
```
import { TextDecoder } from "util";
global["TextDecoder"] = TextDecoder;
```

And now I'm getting a TypeError exception in writableStreamDefaultWriterRelease. 

BTW, should you get back into it, would you be up for including source (and source maps) with this? It'd be easier to debug.

**Comment by zenmumbler** [comment]
Ah, you're using it in Node. I have not spent any time assuring compat with Node beyond a basic test case. There will likely be some weird issues as Nodes built-ins differ from the browser. Don't have the time to address this right now either. I will keep this issue open as a reminder for later. Should work fine in Deno though :)

**Comment by kcoop** [comment]
Yes, Node. Dealt with both issues: the missing TextDecoder just needed to be exposed in the global namespace:

```
import { TextDecoder } from "util";
global["TextDecoder"] = TextDecoder;
```

And the TypeError was actually pilot error - debugger was catching an exception which I mistook to be unhandled.

Thanks again!

**Comment by zenmumbler** [comment]
OK, closing then. Thanks for the feedback!
