### ISSUE TITLE
No types for Compression Streams

### ISSUE THREAD

**Issue by prajaybasu** [stardazed/sd-streams#7]
It seems like the types for `DecompressionStream` and `CompressionStream` are not included in lib yet - the other streams types are. It would make sense to include their type definitions with the polyfill package

**Comment by zenmumbler** [comment]
Good point, I have added global types for `DecompressionStream` and `CompressionStream` and this is part of the new version `2.4.0`. They will become available in your IDE once you do `import "@stardazed/streams-polyfill"` in your entry point source file. Thank you for reporting.
